// Generated by packages/lovdacn/scripts/generate-design-system.cjs. Do not edit.

export const CATALOG_VERSION = "1.0.0" as const
export const WIRE_VERSION = "a" as const
export const BASE62 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" as const

export const WIRE_PRESET_STYLES = [
  "new-york",
  "default",
  "luma",
  "lyra",
  "maia",
  "mira",
  "nova",
  "rhea",
  "sera",
  "vega"
] as const
export const WIRE_PRESET_BASE_COLORS = [
  "zinc",
  "slate",
  "stone",
  "gray",
  "neutral",
  "taupe",
  "mauve",
  "olive",
  "mist"
] as const
export const WIRE_PRESET_THEMES = [
  "zinc",
  "slate",
  "stone",
  "gray",
  "neutral",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose"
] as const
export const WIRE_PRESET_CHART_COLORS = [
  "zinc",
  "slate",
  "stone",
  "gray",
  "neutral",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose"
] as const
export const WIRE_PRESET_FONTS = [
  "inter",
  "dm-sans",
  "nunito-sans",
  "figtree",
  "outfit",
  "manrope",
  "space-grotesk",
  "montserrat",
  "roboto",
  "raleway",
  "public-sans",
  "source-sans-3",
  "lora",
  "merriweather",
  "playfair-display",
  "jetbrains-mono",
  "space-mono",
  "fira-code",
  "noto-serif",
  "roboto-slab",
  "instrument-sans",
  "instrument-serif",
  "geist"
] as const
export const WIRE_PRESET_ICON_LIBRARIES = [
  "lucide",
  "phosphor",
  "tabler",
  "expo",
  "heroicons"
] as const
export const WIRE_PRESET_RADII = [
  "default",
  "none",
  "small",
  "medium",
  "large",
  "full"
] as const

export const PRESET_STYLES = [
  "luma",
  "lyra",
  "maia",
  "mira",
  "nova",
  "rhea",
  "sera",
  "vega"
] as const
export const PRESET_BASE_COLORS = [
  "zinc",
  "slate",
  "stone",
  "gray",
  "neutral",
  "taupe",
  "mauve",
  "olive",
  "mist"
] as const
export const PRESET_THEMES = [
  "zinc",
  "slate",
  "stone",
  "gray",
  "neutral",
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose"
] as const
export const PRESET_CHART_COLORS = PRESET_THEMES
export const PRESET_FONTS = [
  "inter",
  "dm-sans",
  "nunito-sans",
  "figtree",
  "outfit",
  "manrope",
  "space-grotesk",
  "montserrat",
  "roboto",
  "raleway",
  "public-sans",
  "source-sans-3",
  "lora",
  "merriweather",
  "playfair-display",
  "jetbrains-mono",
  "space-mono",
  "fira-code",
  "noto-serif",
  "roboto-slab",
  "instrument-sans",
  "instrument-serif",
  "geist"
] as const
export const PRESET_ICON_LIBRARIES = [
  "lucide",
  "phosphor",
  "tabler"
] as const
export const PRESET_RADII = [
  "default",
  "none",
  "small",
  "medium",
  "large",
  "full"
] as const
export const PRESET_ENGINES = [
  "nativewind",
  "uniwind"
] as const
export const SEMANTIC_ICON_NAMES = [
  "activity",
  "apple",
  "arrow-right",
  "bell",
  "book-open",
  "bot",
  "calendar",
  "chart",
  "check",
  "chevron-down",
  "chevron-down-icon",
  "chevron-left",
  "chevron-right",
  "chevrons-up-down",
  "chevron-up",
  "chevron-up-icon",
  "close",
  "command",
  "credit-card",
  "dollar",
  "error",
  "frame",
  "gallery",
  "git-fork",
  "home",
  "info",
  "layout-dashboard",
  "life-buoy",
  "loader",
  "loader-2",
  "panel-left",
  "success-2",
  "alert-circle",
  "lock",
  "mail",
  "menu",
  "minus",
  "more-horizontal",
  "package",
  "pie-chart",
  "plus",
  "search",
  "settings",
  "settings-2",
  "shopping-cart",
  "square-terminal",
  "success",
  "trending-down",
  "trending-up",
  "user",
  "users",
  "wallet",
  "warning"
] as const

export type PresetStyle = (typeof PRESET_STYLES)[number]
export type PresetBaseColor = (typeof PRESET_BASE_COLORS)[number]
export type PresetTheme = (typeof PRESET_THEMES)[number]
export type PresetFont = (typeof PRESET_FONTS)[number]
export type PresetIconLibrary = (typeof PRESET_ICON_LIBRARIES)[number]
export type PresetRadius = (typeof PRESET_RADII)[number]
export type SemanticIconName = (typeof SEMANTIC_ICON_NAMES)[number]

export type PresetConfig = {
  style: PresetStyle
  baseColor: PresetBaseColor
  theme: PresetTheme
  chartColor: PresetTheme
  font: PresetFont
  iconLibrary: PresetIconLibrary
  radius: PresetRadius
}

export type WirePresetConfigV1 = {
  style: (typeof WIRE_PRESET_STYLES)[number]
  baseColor: (typeof WIRE_PRESET_BASE_COLORS)[number]
  theme: (typeof WIRE_PRESET_THEMES)[number]
  chartColor: (typeof WIRE_PRESET_CHART_COLORS)[number]
  font: (typeof WIRE_PRESET_FONTS)[number]
  iconLibrary: (typeof WIRE_PRESET_ICON_LIBRARIES)[number]
  radius: (typeof WIRE_PRESET_RADII)[number]
}

export type PresetField = keyof PresetConfig
export type PresetNormalization = { config: PresetConfig; warnings: string[] }

export const DEFAULT_PRESET_CONFIG: PresetConfig = {
  "style": "vega",
  "baseColor": "neutral",
  "theme": "cyan",
  "chartColor": "teal",
  "font": "space-grotesk",
  "iconLibrary": "lucide",
  "radius": "medium"
}
export const DEFAULT_CONFIG = DEFAULT_PRESET_CONFIG
export const STYLE_LABELS: Record<PresetStyle, string> = {
  "luma": "Luma",
  "lyra": "Lyra",
  "maia": "Maia",
  "mira": "Mira",
  "nova": "Nova",
  "rhea": "Rhea",
  "sera": "Sera",
  "vega": "Vega"
}
export const FONT_FAMILIES: Record<PresetFont, string> = {
  "inter": "Inter",
  "dm-sans": "DM Sans",
  "nunito-sans": "Nunito Sans",
  "figtree": "Figtree",
  "outfit": "Outfit",
  "manrope": "Manrope",
  "space-grotesk": "Space Grotesk",
  "montserrat": "Montserrat",
  "roboto": "Roboto",
  "raleway": "Raleway",
  "public-sans": "Public Sans",
  "source-sans-3": "Source Sans 3",
  "lora": "Lora",
  "merriweather": "Merriweather",
  "playfair-display": "Playfair Display",
  "jetbrains-mono": "JetBrains Mono",
  "space-mono": "Space Mono",
  "fira-code": "Fira Code",
  "noto-serif": "Noto Serif",
  "roboto-slab": "Roboto Slab",
  "instrument-sans": "Instrument Sans",
  "instrument-serif": "Instrument Serif",
  "geist": "Geist"
}
export const FONT_PACKAGES: Record<PresetFont, string> = {
  "inter": "@expo-google-fonts/inter@0.4.2",
  "dm-sans": "@expo-google-fonts/dm-sans@0.4.2",
  "nunito-sans": "@expo-google-fonts/nunito-sans@0.4.2",
  "figtree": "@expo-google-fonts/figtree@0.4.1",
  "outfit": "@expo-google-fonts/outfit@0.4.3",
  "manrope": "@expo-google-fonts/manrope@0.4.2",
  "space-grotesk": "@expo-google-fonts/space-grotesk@0.4.1",
  "montserrat": "@expo-google-fonts/montserrat@0.4.2",
  "roboto": "@expo-google-fonts/roboto@0.4.3",
  "raleway": "@expo-google-fonts/raleway@0.4.2",
  "public-sans": "@expo-google-fonts/public-sans@0.4.2",
  "source-sans-3": "@expo-google-fonts/source-sans-3@0.4.1",
  "lora": "@expo-google-fonts/lora@0.4.2",
  "merriweather": "@expo-google-fonts/merriweather@0.4.2",
  "playfair-display": "@expo-google-fonts/playfair-display@0.4.2",
  "jetbrains-mono": "@expo-google-fonts/jetbrains-mono@0.4.1",
  "space-mono": "@expo-google-fonts/space-mono@0.4.2",
  "fira-code": "@expo-google-fonts/fira-code@0.4.1",
  "noto-serif": "@expo-google-fonts/noto-serif@0.4.2",
  "roboto-slab": "@expo-google-fonts/roboto-slab@0.4.2",
  "instrument-sans": "@expo-google-fonts/instrument-sans@0.4.2",
  "instrument-serif": "@expo-google-fonts/instrument-serif@0.4.1",
  "geist": "@expo-google-fonts/geist@0.4.2"
}
export const ICON_PACKAGES: Record<PresetIconLibrary, string> = {
  "lucide": "lucide-react-native@1.24.0",
  "phosphor": "phosphor-react-native@3.0.6",
  "tabler": "@tabler/icons-react-native@3.46.0"
}
export const ICON_IMPORTS: Record<PresetIconLibrary, string> = {
  "lucide": "lucide-react-native",
  "phosphor": "phosphor-react-native",
  "tabler": "@tabler/icons-react-native"
}
export const RADIUS_VALUES: Record<PresetRadius, string> = {
  "default": "0.5rem",
  "none": "0rem",
  "small": "0.125rem",
  "medium": "0.625rem",
  "large": "0.75rem",
  "full": "1.5rem"
}
export const FONT_MANIFEST = {
  "inter": {
    "label": "Inter",
    "family": "Inter",
    "category": "sans",
    "package": "@expo-google-fonts/inter",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Inter_400Regular",
      "medium": "Inter_500Medium",
      "semibold": "Inter_600SemiBold",
      "bold": "Inter_700Bold"
    }
  },
  "dm-sans": {
    "label": "DM Sans",
    "family": "DM Sans",
    "category": "sans",
    "package": "@expo-google-fonts/dm-sans",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "DMSans_400Regular",
      "medium": "DMSans_500Medium",
      "semibold": "DMSans_600SemiBold",
      "bold": "DMSans_700Bold"
    }
  },
  "nunito-sans": {
    "label": "Nunito Sans",
    "family": "Nunito Sans",
    "category": "sans",
    "package": "@expo-google-fonts/nunito-sans",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "NunitoSans_400Regular",
      "medium": "NunitoSans_500Medium",
      "semibold": "NunitoSans_600SemiBold",
      "bold": "NunitoSans_700Bold"
    }
  },
  "figtree": {
    "label": "Figtree",
    "family": "Figtree",
    "category": "sans",
    "package": "@expo-google-fonts/figtree",
    "version": "0.4.1",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Figtree_400Regular",
      "medium": "Figtree_500Medium",
      "semibold": "Figtree_600SemiBold",
      "bold": "Figtree_700Bold"
    }
  },
  "outfit": {
    "label": "Outfit",
    "family": "Outfit",
    "category": "sans",
    "package": "@expo-google-fonts/outfit",
    "version": "0.4.3",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Outfit_400Regular",
      "medium": "Outfit_500Medium",
      "semibold": "Outfit_600SemiBold",
      "bold": "Outfit_700Bold"
    }
  },
  "manrope": {
    "label": "Manrope",
    "family": "Manrope",
    "category": "sans",
    "package": "@expo-google-fonts/manrope",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Manrope_400Regular",
      "medium": "Manrope_500Medium",
      "semibold": "Manrope_600SemiBold",
      "bold": "Manrope_700Bold"
    }
  },
  "space-grotesk": {
    "label": "Space Grotesk",
    "family": "Space Grotesk",
    "category": "sans",
    "package": "@expo-google-fonts/space-grotesk",
    "version": "0.4.1",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "SpaceGrotesk_400Regular",
      "medium": "SpaceGrotesk_500Medium",
      "semibold": "SpaceGrotesk_600SemiBold",
      "bold": "SpaceGrotesk_700Bold"
    }
  },
  "montserrat": {
    "label": "Montserrat",
    "family": "Montserrat",
    "category": "sans",
    "package": "@expo-google-fonts/montserrat",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Montserrat_400Regular",
      "medium": "Montserrat_500Medium",
      "semibold": "Montserrat_600SemiBold",
      "bold": "Montserrat_700Bold"
    }
  },
  "roboto": {
    "label": "Roboto",
    "family": "Roboto",
    "category": "sans",
    "package": "@expo-google-fonts/roboto",
    "version": "0.4.3",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Roboto_400Regular",
      "medium": "Roboto_500Medium",
      "semibold": "Roboto_600SemiBold",
      "bold": "Roboto_700Bold"
    }
  },
  "raleway": {
    "label": "Raleway",
    "family": "Raleway",
    "category": "sans",
    "package": "@expo-google-fonts/raleway",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Raleway_400Regular",
      "medium": "Raleway_500Medium",
      "semibold": "Raleway_600SemiBold",
      "bold": "Raleway_700Bold"
    }
  },
  "public-sans": {
    "label": "Public Sans",
    "family": "Public Sans",
    "category": "sans",
    "package": "@expo-google-fonts/public-sans",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "PublicSans_400Regular",
      "medium": "PublicSans_500Medium",
      "semibold": "PublicSans_600SemiBold",
      "bold": "PublicSans_700Bold"
    }
  },
  "source-sans-3": {
    "label": "Source Sans 3",
    "family": "Source Sans 3",
    "category": "sans",
    "package": "@expo-google-fonts/source-sans-3",
    "version": "0.4.1",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "SourceSans3_400Regular",
      "medium": "SourceSans3_500Medium",
      "semibold": "SourceSans3_600SemiBold",
      "bold": "SourceSans3_700Bold"
    }
  },
  "lora": {
    "label": "Lora",
    "family": "Lora",
    "category": "serif",
    "package": "@expo-google-fonts/lora",
    "version": "0.4.2",
    "fallback": "Georgia, 'Times New Roman', serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Lora_400Regular",
      "medium": "Lora_500Medium",
      "semibold": "Lora_600SemiBold",
      "bold": "Lora_700Bold"
    }
  },
  "merriweather": {
    "label": "Merriweather",
    "family": "Merriweather",
    "category": "serif",
    "package": "@expo-google-fonts/merriweather",
    "version": "0.4.2",
    "fallback": "Georgia, 'Times New Roman', serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Merriweather_400Regular",
      "medium": "Merriweather_500Medium",
      "semibold": "Merriweather_600SemiBold",
      "bold": "Merriweather_700Bold"
    }
  },
  "playfair-display": {
    "label": "Playfair Display",
    "family": "Playfair Display",
    "category": "serif",
    "package": "@expo-google-fonts/playfair-display",
    "version": "0.4.2",
    "fallback": "Georgia, 'Times New Roman', serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "PlayfairDisplay_400Regular",
      "medium": "PlayfairDisplay_500Medium",
      "semibold": "PlayfairDisplay_600SemiBold",
      "bold": "PlayfairDisplay_700Bold"
    }
  },
  "jetbrains-mono": {
    "label": "JetBrains Mono",
    "family": "JetBrains Mono",
    "category": "mono",
    "package": "@expo-google-fonts/jetbrains-mono",
    "version": "0.4.1",
    "fallback": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "JetBrainsMono_400Regular",
      "medium": "JetBrainsMono_500Medium",
      "semibold": "JetBrainsMono_600SemiBold",
      "bold": "JetBrainsMono_700Bold"
    }
  },
  "space-mono": {
    "label": "Space Mono",
    "family": "Space Mono",
    "category": "mono",
    "package": "@expo-google-fonts/space-mono",
    "version": "0.4.2",
    "fallback": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "availableWeights": [
      400,
      700
    ],
    "faces": {
      "regular": "SpaceMono_400Regular",
      "medium": "SpaceMono_400Regular",
      "semibold": "SpaceMono_700Bold",
      "bold": "SpaceMono_700Bold"
    }
  },
  "fira-code": {
    "label": "Fira Code",
    "family": "Fira Code",
    "category": "mono",
    "package": "@expo-google-fonts/fira-code",
    "version": "0.4.1",
    "fallback": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "FiraCode_400Regular",
      "medium": "FiraCode_500Medium",
      "semibold": "FiraCode_600SemiBold",
      "bold": "FiraCode_700Bold"
    }
  },
  "noto-serif": {
    "label": "Noto Serif",
    "family": "Noto Serif",
    "category": "serif",
    "package": "@expo-google-fonts/noto-serif",
    "version": "0.4.2",
    "fallback": "Georgia, 'Times New Roman', serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "NotoSerif_400Regular",
      "medium": "NotoSerif_500Medium",
      "semibold": "NotoSerif_600SemiBold",
      "bold": "NotoSerif_700Bold"
    }
  },
  "roboto-slab": {
    "label": "Roboto Slab",
    "family": "Roboto Slab",
    "category": "serif",
    "package": "@expo-google-fonts/roboto-slab",
    "version": "0.4.2",
    "fallback": "Georgia, 'Times New Roman', serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "RobotoSlab_400Regular",
      "medium": "RobotoSlab_500Medium",
      "semibold": "RobotoSlab_600SemiBold",
      "bold": "RobotoSlab_700Bold"
    }
  },
  "instrument-sans": {
    "label": "Instrument Sans",
    "family": "Instrument Sans",
    "category": "sans",
    "package": "@expo-google-fonts/instrument-sans",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "InstrumentSans_400Regular",
      "medium": "InstrumentSans_500Medium",
      "semibold": "InstrumentSans_600SemiBold",
      "bold": "InstrumentSans_700Bold"
    }
  },
  "instrument-serif": {
    "label": "Instrument Serif",
    "family": "Instrument Serif",
    "category": "serif",
    "package": "@expo-google-fonts/instrument-serif",
    "version": "0.4.1",
    "fallback": "Georgia, 'Times New Roman', serif",
    "availableWeights": [
      400
    ],
    "faces": {
      "regular": "InstrumentSerif_400Regular",
      "medium": "InstrumentSerif_400Regular",
      "semibold": "InstrumentSerif_400Regular",
      "bold": "InstrumentSerif_400Regular"
    }
  },
  "geist": {
    "label": "Geist",
    "family": "Geist",
    "category": "sans",
    "package": "@expo-google-fonts/geist",
    "version": "0.4.2",
    "fallback": "ui-sans-serif, system-ui, sans-serif",
    "availableWeights": [
      400,
      500,
      600,
      700
    ],
    "faces": {
      "regular": "Geist_400Regular",
      "medium": "Geist_500Medium",
      "semibold": "Geist_600SemiBold",
      "bold": "Geist_700Bold"
    }
  }
} as const
export const ICON_LIBRARY_MANIFEST = {
  "lucide": {
    "label": "Lucide",
    "package": "lucide-react-native",
    "version": "1.24.0"
  },
  "phosphor": {
    "label": "Phosphor",
    "package": "phosphor-react-native",
    "version": "3.0.6"
  },
  "tabler": {
    "label": "Tabler",
    "package": "@tabler/icons-react-native",
    "version": "3.46.0"
  }
} as const
export const STYLE_METADATA = {
  "luma": {
    "layout": {
      "pagePaddingX": 24,
      "pagePaddingBottom": 56,
      "grid": "-mx-3 gap-y-7",
      "column": "px-3 gap-7",
      "stackXs": "gap-1.5",
      "stackSm": "gap-2",
      "stackMd": "gap-4",
      "stackLg": "gap-6",
      "field": "gap-2",
      "inline": "gap-2",
      "section": "gap-5"
    },
    "typography": {
      "display": "text-3xl font-bold tracking-tight",
      "heading": "text-xl font-semibold tracking-tight",
      "cardTitle": "text-lg font-semibold tracking-tight",
      "dialogTitle": "text-lg font-semibold",
      "body": "text-sm leading-relaxed",
      "label": "text-sm font-medium",
      "caption": "text-xs leading-relaxed",
      "metric": "text-2xl font-bold tracking-tight",
      "menuItem": "text-sm font-medium",
      "badge": "text-xs font-medium",
      "button": "text-sm font-medium",
      "code": "text-xs font-medium"
    },
    "icon": {
      "size": 16,
      "strokeWidth": 2,
      "weight": "regular"
    }
  },
  "lyra": {
    "layout": {
      "pagePaddingX": 18,
      "pagePaddingBottom": 40,
      "grid": "-mx-2 gap-y-4",
      "column": "px-2 gap-4",
      "stackXs": "gap-1",
      "stackSm": "gap-1.5",
      "stackMd": "gap-3",
      "stackLg": "gap-4",
      "field": "gap-1",
      "inline": "gap-1.5",
      "section": "gap-3"
    },
    "typography": {
      "display": "text-2xl font-semibold tracking-tight",
      "heading": "text-base font-semibold tracking-tight",
      "cardTitle": "text-sm font-semibold tracking-tight",
      "dialogTitle": "text-sm font-semibold",
      "body": "text-xs leading-relaxed",
      "label": "text-xs font-medium",
      "caption": "text-[10px] leading-relaxed",
      "metric": "text-xl font-semibold tracking-tight",
      "menuItem": "text-xs font-medium",
      "badge": "text-[10px] font-medium uppercase tracking-wide",
      "button": "text-xs font-medium",
      "code": "text-xs font-medium"
    },
    "icon": {
      "size": 14,
      "strokeWidth": 1.75,
      "weight": "regular"
    }
  },
  "maia": {
    "layout": {
      "pagePaddingX": 28,
      "pagePaddingBottom": 64,
      "grid": "-mx-4 gap-y-8",
      "column": "px-4 gap-8",
      "stackXs": "gap-2",
      "stackSm": "gap-3",
      "stackMd": "gap-5",
      "stackLg": "gap-8",
      "field": "gap-2.5",
      "inline": "gap-2.5",
      "section": "gap-6"
    },
    "typography": {
      "display": "text-4xl font-semibold tracking-tight",
      "heading": "text-2xl font-semibold tracking-tight",
      "cardTitle": "text-lg font-medium tracking-tight",
      "dialogTitle": "text-lg font-medium",
      "body": "text-sm leading-relaxed",
      "label": "text-sm font-medium",
      "caption": "text-xs leading-relaxed",
      "metric": "text-3xl font-semibold tracking-tight",
      "menuItem": "text-sm font-medium",
      "badge": "text-xs font-medium",
      "button": "text-sm font-medium",
      "code": "text-xs font-medium"
    },
    "icon": {
      "size": 17,
      "strokeWidth": 1.8,
      "weight": "regular"
    }
  },
  "mira": {
    "layout": {
      "pagePaddingX": 16,
      "pagePaddingBottom": 36,
      "grid": "-mx-1.5 gap-y-3",
      "column": "px-1.5 gap-3",
      "stackXs": "gap-0.5",
      "stackSm": "gap-1",
      "stackMd": "gap-2",
      "stackLg": "gap-3",
      "field": "gap-1",
      "inline": "gap-1",
      "section": "gap-2"
    },
    "typography": {
      "display": "text-xl font-semibold tracking-tight",
      "heading": "text-base font-medium tracking-tight",
      "cardTitle": "text-sm font-medium",
      "dialogTitle": "text-sm font-medium",
      "body": "text-xs leading-relaxed",
      "label": "text-xs font-medium",
      "caption": "text-[10px] leading-relaxed",
      "metric": "text-xl font-semibold tracking-tight",
      "menuItem": "text-xs font-medium",
      "badge": "text-[10px] font-medium",
      "button": "text-xs font-medium",
      "code": "text-[10px] font-medium"
    },
    "icon": {
      "size": 14,
      "strokeWidth": 1.75,
      "weight": "regular"
    }
  },
  "nova": {
    "layout": {
      "pagePaddingX": 20,
      "pagePaddingBottom": 44,
      "grid": "-mx-2 gap-y-4",
      "column": "px-2 gap-4",
      "stackXs": "gap-1",
      "stackSm": "gap-1.5",
      "stackMd": "gap-3",
      "stackLg": "gap-4",
      "field": "gap-1.5",
      "inline": "gap-1.5",
      "section": "gap-3"
    },
    "typography": {
      "display": "text-2xl font-semibold tracking-tight",
      "heading": "text-lg font-semibold tracking-tight",
      "cardTitle": "text-base font-medium tracking-tight",
      "dialogTitle": "text-base font-medium",
      "body": "text-sm leading-snug",
      "label": "text-xs font-medium",
      "caption": "text-xs leading-snug",
      "metric": "text-2xl font-semibold tracking-tight",
      "menuItem": "text-xs font-medium",
      "badge": "text-xs font-medium",
      "button": "text-xs font-medium",
      "code": "text-xs font-medium"
    },
    "icon": {
      "size": 15,
      "strokeWidth": 2,
      "weight": "regular"
    }
  },
  "rhea": {
    "layout": {
      "pagePaddingX": 24,
      "pagePaddingBottom": 56,
      "grid": "-mx-3 gap-y-6",
      "column": "px-3 gap-6",
      "stackXs": "gap-1.5",
      "stackSm": "gap-2",
      "stackMd": "gap-4",
      "stackLg": "gap-6",
      "field": "gap-2",
      "inline": "gap-2",
      "section": "gap-5"
    },
    "typography": {
      "display": "text-3xl font-bold tracking-tight",
      "heading": "text-xl font-semibold tracking-tight",
      "cardTitle": "text-lg font-semibold tracking-tight",
      "dialogTitle": "text-lg font-semibold",
      "body": "text-sm leading-relaxed",
      "label": "text-sm font-semibold",
      "caption": "text-xs leading-relaxed",
      "metric": "text-2xl font-bold tracking-tight",
      "menuItem": "text-sm font-medium",
      "badge": "text-xs font-semibold",
      "button": "text-sm font-semibold",
      "code": "text-xs font-medium"
    },
    "icon": {
      "size": 16,
      "strokeWidth": 2.25,
      "weight": "bold"
    }
  },
  "sera": {
    "layout": {
      "pagePaddingX": 32,
      "pagePaddingBottom": 72,
      "grid": "-mx-4 gap-y-8",
      "column": "px-4 gap-8",
      "stackXs": "gap-2",
      "stackSm": "gap-3",
      "stackMd": "gap-5",
      "stackLg": "gap-8",
      "field": "gap-2.5",
      "inline": "gap-3",
      "section": "gap-6"
    },
    "typography": {
      "display": "text-4xl font-semibold uppercase tracking-widest",
      "heading": "text-2xl font-semibold uppercase tracking-wider",
      "cardTitle": "text-lg font-semibold uppercase tracking-wider",
      "dialogTitle": "text-lg font-semibold uppercase tracking-wider",
      "body": "text-sm leading-relaxed",
      "label": "text-xs font-semibold uppercase tracking-wide",
      "caption": "text-xs leading-relaxed",
      "metric": "text-3xl font-semibold tracking-tight",
      "menuItem": "text-xs font-semibold uppercase tracking-wide",
      "badge": "text-[10px] font-semibold uppercase tracking-widest",
      "button": "text-xs font-semibold uppercase tracking-widest",
      "code": "text-xs font-semibold tracking-wide"
    },
    "icon": {
      "size": 15,
      "strokeWidth": 1.5,
      "weight": "regular"
    }
  },
  "vega": {
    "layout": {
      "pagePaddingX": 24,
      "pagePaddingBottom": 52,
      "grid": "-mx-3 gap-y-6",
      "column": "px-3 gap-6",
      "stackXs": "gap-1.5",
      "stackSm": "gap-2",
      "stackMd": "gap-4",
      "stackLg": "gap-6",
      "field": "gap-1.5",
      "inline": "gap-2",
      "section": "gap-4"
    },
    "typography": {
      "display": "text-3xl font-semibold tracking-tight",
      "heading": "text-xl font-semibold tracking-tight",
      "cardTitle": "text-lg font-semibold tracking-tight",
      "dialogTitle": "text-lg font-semibold",
      "body": "text-sm leading-relaxed",
      "label": "text-sm font-medium",
      "caption": "text-xs leading-relaxed",
      "metric": "text-2xl font-semibold tracking-tight",
      "menuItem": "text-sm font-medium",
      "badge": "text-xs font-medium",
      "button": "text-sm font-medium",
      "code": "text-xs font-medium"
    },
    "icon": {
      "size": 16,
      "strokeWidth": 2,
      "weight": "regular"
    }
  }
} as const
export const BLOCK_RECIPES = {
  "luma": {
    "page": "px-6 py-8",
    "grid": "gap-7",
    "column": "gap-7",
    "section": "gap-5",
    "fieldGroup": "gap-4"
  },
  "lyra": {
    "page": "px-4 py-5",
    "grid": "gap-4",
    "column": "gap-4",
    "section": "gap-3",
    "fieldGroup": "gap-3"
  },
  "maia": {
    "page": "px-8 py-10",
    "grid": "gap-8",
    "column": "gap-8",
    "section": "gap-6",
    "fieldGroup": "gap-5"
  },
  "mira": {
    "page": "px-4 py-4",
    "grid": "gap-3",
    "column": "gap-3",
    "section": "gap-2",
    "fieldGroup": "gap-2"
  },
  "nova": {
    "page": "px-5 py-6",
    "grid": "gap-4",
    "column": "gap-4",
    "section": "gap-3",
    "fieldGroup": "gap-3"
  },
  "rhea": {
    "page": "px-6 py-8",
    "grid": "gap-6",
    "column": "gap-6",
    "section": "gap-5",
    "fieldGroup": "gap-4"
  },
  "sera": {
    "page": "px-8 py-12",
    "grid": "gap-8",
    "column": "gap-8",
    "section": "gap-6",
    "fieldGroup": "gap-5"
  },
  "vega": {
    "page": "px-6 py-8",
    "grid": "gap-6",
    "column": "gap-6",
    "section": "gap-4",
    "fieldGroup": "gap-4"
  }
} as const

export type NamedPreset = PresetConfig & { title: string; description: string }
export const DEFAULT_PRESETS: Record<PresetStyle, NamedPreset> = {
  "luma": {
    "title": "Luma",
    "description": "Lucide / Inter / Soft, rounded, comfortable",
    "style": "luma",
    "baseColor": "neutral",
    "theme": "blue",
    "chartColor": "sky",
    "font": "inter",
    "iconLibrary": "lucide",
    "radius": "large"
  },
  "lyra": {
    "title": "Lyra",
    "description": "Phosphor / JetBrains Mono / Technical, compact, square",
    "style": "lyra",
    "baseColor": "stone",
    "theme": "amber",
    "chartColor": "orange",
    "font": "jetbrains-mono",
    "iconLibrary": "phosphor",
    "radius": "small"
  },
  "maia": {
    "title": "Maia",
    "description": "Tabler / Figtree / Spacious and strongly rounded",
    "style": "maia",
    "baseColor": "neutral",
    "theme": "violet",
    "chartColor": "purple",
    "font": "figtree",
    "iconLibrary": "tabler",
    "radius": "large"
  },
  "mira": {
    "title": "Mira",
    "description": "Phosphor / Inter / Dense, compact controls and type",
    "style": "mira",
    "baseColor": "zinc",
    "theme": "emerald",
    "chartColor": "red",
    "font": "inter",
    "iconLibrary": "phosphor",
    "radius": "full"
  },
  "nova": {
    "title": "Nova",
    "description": "Lucide / Inter / Compact, restrained, tight cards",
    "style": "nova",
    "baseColor": "neutral",
    "theme": "neutral",
    "chartColor": "blue",
    "font": "inter",
    "iconLibrary": "lucide",
    "radius": "small"
  },
  "rhea": {
    "title": "Rhea",
    "description": "Lucide / DM Sans / Soft, pill-oriented, approachable",
    "style": "rhea",
    "baseColor": "neutral",
    "theme": "rose",
    "chartColor": "pink",
    "font": "dm-sans",
    "iconLibrary": "lucide",
    "radius": "full"
  },
  "sera": {
    "title": "Sera",
    "description": "Lucide / Playfair Display / Editorial, square, uppercase accents",
    "style": "sera",
    "baseColor": "taupe",
    "theme": "amber",
    "chartColor": "amber",
    "font": "playfair-display",
    "iconLibrary": "lucide",
    "radius": "none"
  },
  "vega": {
    "title": "Vega",
    "description": "Lucide / Space Grotesk / Balanced, classic default",
    "style": "vega",
    "baseColor": "neutral",
    "theme": "cyan",
    "chartColor": "teal",
    "font": "space-grotesk",
    "iconLibrary": "lucide",
    "radius": "medium"
  }
}

export const STYLE_ALIASES: Readonly<Record<string, PresetStyle>> = {
  "default": "vega",
  "new-york": "vega"
}
export const ICON_LIBRARY_ALIASES: Readonly<Record<string, PresetIconLibrary>> = {
  "expo": "lucide",
  "heroicons": "lucide"
}
export const FONT_ALIASES: Readonly<Record<string, PresetFont>> = {}

const PRESET_FIELDS_V1 = [
  { key: 'style', values: WIRE_PRESET_STYLES, bits: 4 },
  { key: 'baseColor', values: WIRE_PRESET_BASE_COLORS, bits: 4 },
  { key: 'theme', values: WIRE_PRESET_THEMES, bits: 5 },
  { key: 'chartColor', values: WIRE_PRESET_CHART_COLORS, bits: 5 },
  { key: 'font', values: WIRE_PRESET_FONTS, bits: 5 },
  { key: 'iconLibrary', values: WIRE_PRESET_ICON_LIBRARIES, bits: 3 },
  { key: 'radius', values: WIRE_PRESET_RADII, bits: 3 },
] as const

function normalizeValue<T extends readonly string[]>(
  value: unknown,
  active: T,
  aliases: Readonly<Record<string, T[number]>>,
  fallback: T[number],
  field: string,
  warnings: string[]
): T[number] {
  const candidate = typeof value === 'string' ? value : ''
  if ((active as readonly string[]).includes(candidate)) return candidate as T[number]
  const normalized = aliases[candidate]
  if (normalized && (active as readonly string[]).includes(normalized)) {
    warnings.push(field + ' "' + candidate + '" is legacy and was normalized to "' + normalized + '"')
    return normalized
  }
  if (candidate) warnings.push('Unknown ' + field + ' "' + candidate + '"; using "' + fallback + '"')
  return fallback
}

export function normalizePreset(input: Partial<Record<PresetField, unknown>>): PresetNormalization {
  const warnings: string[] = []
  return {
    config: {
      style: normalizeValue(input.style, PRESET_STYLES, STYLE_ALIASES, DEFAULT_PRESET_CONFIG.style, 'style', warnings),
      baseColor: normalizeValue(input.baseColor, PRESET_BASE_COLORS, {}, DEFAULT_PRESET_CONFIG.baseColor, 'base color', warnings),
      theme: normalizeValue(input.theme, PRESET_THEMES, {}, DEFAULT_PRESET_CONFIG.theme, 'theme', warnings),
      chartColor: normalizeValue(input.chartColor, PRESET_CHART_COLORS, {}, DEFAULT_PRESET_CONFIG.chartColor, 'chart color', warnings),
      font: normalizeValue(input.font, PRESET_FONTS, FONT_ALIASES, DEFAULT_PRESET_CONFIG.font, 'font', warnings),
      iconLibrary: normalizeValue(input.iconLibrary, PRESET_ICON_LIBRARIES, ICON_LIBRARY_ALIASES, DEFAULT_PRESET_CONFIG.iconLibrary, 'icon library', warnings),
      radius: normalizeValue(input.radius, PRESET_RADII, {}, DEFAULT_PRESET_CONFIG.radius, 'radius', warnings),
    },
    warnings,
  }
}

export const normalizePresetConfig = (input: Partial<Record<PresetField, unknown>>) => normalizePreset(input).config

export function toBase62(num: number): string {
  if (num === 0) return '0'
  let result = ''
  let value = num
  while (value > 0) {
    result = BASE62.charAt(value % 62) + result
    value = Math.floor(value / 62)
  }
  return result
}

export function fromBase62(value: string): number {
  let result = 0
  for (const character of value) {
    const index = BASE62.indexOf(character)
    if (index === -1) return -1
    result = result * 62 + index
  }
  return result
}

export function encodePreset(config: Partial<PresetConfig>): string {
  const merged = normalizePreset({ ...DEFAULT_PRESET_CONFIG, ...config }).config
  let bits = 0
  let offset = 0
  for (const field of PRESET_FIELDS_V1) {
    const index = (field.values as readonly string[]).indexOf(merged[field.key] as string)
    bits += (index === -1 ? 0 : index) * 2 ** offset
    offset += field.bits
  }
  return WIRE_VERSION + toBase62(bits)
}

export function decodeWirePresetV1(code: string): WirePresetConfigV1 | null {
  if (!code || code.length < 2 || code.charAt(0) !== WIRE_VERSION) return null
  const bits = fromBase62(code.slice(1))
  if (bits < 0) return null
  const result: Record<string, string> = {}
  let offset = 0
  for (const field of PRESET_FIELDS_V1) {
    const index = Math.floor(bits / 2 ** offset) % 2 ** field.bits
    const values = field.values as readonly string[]
    result[field.key] = index < values.length ? values[index]! : values[0]!
    offset += field.bits
  }
  return result as WirePresetConfigV1
}

export function decodePresetWithWarnings(code: string): PresetNormalization | null {
  const wireConfig = decodeWirePresetV1(code)
  return wireConfig ? normalizePreset(wireConfig) : null
}

export function decodePreset(code: string): PresetConfig | null {
  return decodePresetWithWarnings(code)?.config ?? null
}

export function isPresetCode(value: string): boolean {
  if (!value || value.length < 2 || value.length > 8 || value.charAt(0) !== WIRE_VERSION) return false
  for (let index = 1; index < value.length; index += 1) {
    if (BASE62.indexOf(value.charAt(index)) === -1) return false
  }
  return true
}

export function isValidPreset(value: string): boolean {
  return decodeWirePresetV1(value) !== null
}

export function randomizeConfig(
  current: PresetConfig = DEFAULT_PRESET_CONFIG,
  locked: Partial<Record<PresetField, boolean>> = {}
): PresetConfig {
  const pick = <T,>(values: readonly T[]): T => values[Math.floor(Math.random() * values.length)]!
  return {
    style: locked.style ? current.style : pick(PRESET_STYLES),
    baseColor: locked.baseColor ? current.baseColor : pick(PRESET_BASE_COLORS),
    theme: locked.theme ? current.theme : pick(PRESET_THEMES),
    chartColor: locked.chartColor ? current.chartColor : pick(PRESET_CHART_COLORS),
    font: locked.font ? current.font : pick(PRESET_FONTS),
    iconLibrary: locked.iconLibrary ? current.iconLibrary : pick(PRESET_ICON_LIBRARIES),
    radius: locked.radius ? current.radius : pick(PRESET_RADII),
  }
}

export const generateRandomConfig = () => randomizeConfig()
export const generateRandomPreset = () => encodePreset(generateRandomConfig())

export const SERIF_FONTS = new Set<PresetFont>([
  "lora",
  "merriweather",
  "playfair-display",
  "noto-serif",
  "roboto-slab",
  "instrument-serif"
])
export const MONO_FONTS = new Set<PresetFont>([
  "jetbrains-mono",
  "space-mono",
  "fira-code"
])
export function getFontCategory(font: PresetFont): 'sans' | 'serif' | 'mono' {
  if (SERIF_FONTS.has(font)) return 'serif'
  if (MONO_FONTS.has(font)) return 'mono'
  return 'sans'
}
