// Generated by packages/lovdacn/scripts/generate-design-system.cjs. Do not edit.

import * as Font from 'expo-font'

import type { PresetFont } from '@/lib/generated/preset-catalog'

export type FontWeightRole = 'regular' | 'medium' | 'semibold' | 'bold'
export type LoadedFontFaces = Readonly<Record<FontWeightRole, string>>

const LOADERS: Record<PresetFont, () => Promise<LoadedFontFaces>> = {
  "inter": async () => {
    const module = await import("@expo-google-fonts/inter")
    const sources = { regular: module.Inter_400Regular, medium: module.Inter_500Medium, semibold: module.Inter_600SemiBold, bold: module.Inter_700Bold }
    const aliases = { regular: "Inter_400Regular", medium: "Inter_500Medium", semibold: "Inter_600SemiBold", bold: "Inter_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "dm-sans": async () => {
    const module = await import("@expo-google-fonts/dm-sans")
    const sources = { regular: module.DMSans_400Regular, medium: module.DMSans_500Medium, semibold: module.DMSans_600SemiBold, bold: module.DMSans_700Bold }
    const aliases = { regular: "DMSans_400Regular", medium: "DMSans_500Medium", semibold: "DMSans_600SemiBold", bold: "DMSans_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "nunito-sans": async () => {
    const module = await import("@expo-google-fonts/nunito-sans")
    const sources = { regular: module.NunitoSans_400Regular, medium: module.NunitoSans_500Medium, semibold: module.NunitoSans_600SemiBold, bold: module.NunitoSans_700Bold }
    const aliases = { regular: "NunitoSans_400Regular", medium: "NunitoSans_500Medium", semibold: "NunitoSans_600SemiBold", bold: "NunitoSans_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "figtree": async () => {
    const module = await import("@expo-google-fonts/figtree")
    const sources = { regular: module.Figtree_400Regular, medium: module.Figtree_500Medium, semibold: module.Figtree_600SemiBold, bold: module.Figtree_700Bold }
    const aliases = { regular: "Figtree_400Regular", medium: "Figtree_500Medium", semibold: "Figtree_600SemiBold", bold: "Figtree_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "outfit": async () => {
    const module = await import("@expo-google-fonts/outfit")
    const sources = { regular: module.Outfit_400Regular, medium: module.Outfit_500Medium, semibold: module.Outfit_600SemiBold, bold: module.Outfit_700Bold }
    const aliases = { regular: "Outfit_400Regular", medium: "Outfit_500Medium", semibold: "Outfit_600SemiBold", bold: "Outfit_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "manrope": async () => {
    const module = await import("@expo-google-fonts/manrope")
    const sources = { regular: module.Manrope_400Regular, medium: module.Manrope_500Medium, semibold: module.Manrope_600SemiBold, bold: module.Manrope_700Bold }
    const aliases = { regular: "Manrope_400Regular", medium: "Manrope_500Medium", semibold: "Manrope_600SemiBold", bold: "Manrope_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "space-grotesk": async () => {
    const module = await import("@expo-google-fonts/space-grotesk")
    const sources = { regular: module.SpaceGrotesk_400Regular, medium: module.SpaceGrotesk_500Medium, semibold: module.SpaceGrotesk_600SemiBold, bold: module.SpaceGrotesk_700Bold }
    const aliases = { regular: "SpaceGrotesk_400Regular", medium: "SpaceGrotesk_500Medium", semibold: "SpaceGrotesk_600SemiBold", bold: "SpaceGrotesk_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "montserrat": async () => {
    const module = await import("@expo-google-fonts/montserrat")
    const sources = { regular: module.Montserrat_400Regular, medium: module.Montserrat_500Medium, semibold: module.Montserrat_600SemiBold, bold: module.Montserrat_700Bold }
    const aliases = { regular: "Montserrat_400Regular", medium: "Montserrat_500Medium", semibold: "Montserrat_600SemiBold", bold: "Montserrat_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "roboto": async () => {
    const module = await import("@expo-google-fonts/roboto")
    const sources = { regular: module.Roboto_400Regular, medium: module.Roboto_500Medium, semibold: module.Roboto_600SemiBold, bold: module.Roboto_700Bold }
    const aliases = { regular: "Roboto_400Regular", medium: "Roboto_500Medium", semibold: "Roboto_600SemiBold", bold: "Roboto_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "raleway": async () => {
    const module = await import("@expo-google-fonts/raleway")
    const sources = { regular: module.Raleway_400Regular, medium: module.Raleway_500Medium, semibold: module.Raleway_600SemiBold, bold: module.Raleway_700Bold }
    const aliases = { regular: "Raleway_400Regular", medium: "Raleway_500Medium", semibold: "Raleway_600SemiBold", bold: "Raleway_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "public-sans": async () => {
    const module = await import("@expo-google-fonts/public-sans")
    const sources = { regular: module.PublicSans_400Regular, medium: module.PublicSans_500Medium, semibold: module.PublicSans_600SemiBold, bold: module.PublicSans_700Bold }
    const aliases = { regular: "PublicSans_400Regular", medium: "PublicSans_500Medium", semibold: "PublicSans_600SemiBold", bold: "PublicSans_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "source-sans-3": async () => {
    const module = await import("@expo-google-fonts/source-sans-3")
    const sources = { regular: module.SourceSans3_400Regular, medium: module.SourceSans3_500Medium, semibold: module.SourceSans3_600SemiBold, bold: module.SourceSans3_700Bold }
    const aliases = { regular: "SourceSans3_400Regular", medium: "SourceSans3_500Medium", semibold: "SourceSans3_600SemiBold", bold: "SourceSans3_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "lora": async () => {
    const module = await import("@expo-google-fonts/lora")
    const sources = { regular: module.Lora_400Regular, medium: module.Lora_500Medium, semibold: module.Lora_600SemiBold, bold: module.Lora_700Bold }
    const aliases = { regular: "Lora_400Regular", medium: "Lora_500Medium", semibold: "Lora_600SemiBold", bold: "Lora_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "merriweather": async () => {
    const module = await import("@expo-google-fonts/merriweather")
    const sources = { regular: module.Merriweather_400Regular, medium: module.Merriweather_500Medium, semibold: module.Merriweather_600SemiBold, bold: module.Merriweather_700Bold }
    const aliases = { regular: "Merriweather_400Regular", medium: "Merriweather_500Medium", semibold: "Merriweather_600SemiBold", bold: "Merriweather_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "playfair-display": async () => {
    const module = await import("@expo-google-fonts/playfair-display")
    const sources = { regular: module.PlayfairDisplay_400Regular, medium: module.PlayfairDisplay_500Medium, semibold: module.PlayfairDisplay_600SemiBold, bold: module.PlayfairDisplay_700Bold }
    const aliases = { regular: "PlayfairDisplay_400Regular", medium: "PlayfairDisplay_500Medium", semibold: "PlayfairDisplay_600SemiBold", bold: "PlayfairDisplay_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "jetbrains-mono": async () => {
    const module = await import("@expo-google-fonts/jetbrains-mono")
    const sources = { regular: module.JetBrainsMono_400Regular, medium: module.JetBrainsMono_500Medium, semibold: module.JetBrainsMono_600SemiBold, bold: module.JetBrainsMono_700Bold }
    const aliases = { regular: "JetBrainsMono_400Regular", medium: "JetBrainsMono_500Medium", semibold: "JetBrainsMono_600SemiBold", bold: "JetBrainsMono_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "space-mono": async () => {
    const module = await import("@expo-google-fonts/space-mono")
    const sources = { regular: module.SpaceMono_400Regular, medium: module.SpaceMono_400Regular, semibold: module.SpaceMono_700Bold, bold: module.SpaceMono_700Bold }
    const aliases = { regular: "SpaceMono_400Regular", medium: "SpaceMono_400Regular", semibold: "SpaceMono_700Bold", bold: "SpaceMono_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "fira-code": async () => {
    const module = await import("@expo-google-fonts/fira-code")
    const sources = { regular: module.FiraCode_400Regular, medium: module.FiraCode_500Medium, semibold: module.FiraCode_600SemiBold, bold: module.FiraCode_700Bold }
    const aliases = { regular: "FiraCode_400Regular", medium: "FiraCode_500Medium", semibold: "FiraCode_600SemiBold", bold: "FiraCode_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "noto-serif": async () => {
    const module = await import("@expo-google-fonts/noto-serif")
    const sources = { regular: module.NotoSerif_400Regular, medium: module.NotoSerif_500Medium, semibold: module.NotoSerif_600SemiBold, bold: module.NotoSerif_700Bold }
    const aliases = { regular: "NotoSerif_400Regular", medium: "NotoSerif_500Medium", semibold: "NotoSerif_600SemiBold", bold: "NotoSerif_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "roboto-slab": async () => {
    const module = await import("@expo-google-fonts/roboto-slab")
    const sources = { regular: module.RobotoSlab_400Regular, medium: module.RobotoSlab_500Medium, semibold: module.RobotoSlab_600SemiBold, bold: module.RobotoSlab_700Bold }
    const aliases = { regular: "RobotoSlab_400Regular", medium: "RobotoSlab_500Medium", semibold: "RobotoSlab_600SemiBold", bold: "RobotoSlab_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "instrument-sans": async () => {
    const module = await import("@expo-google-fonts/instrument-sans")
    const sources = { regular: module.InstrumentSans_400Regular, medium: module.InstrumentSans_500Medium, semibold: module.InstrumentSans_600SemiBold, bold: module.InstrumentSans_700Bold }
    const aliases = { regular: "InstrumentSans_400Regular", medium: "InstrumentSans_500Medium", semibold: "InstrumentSans_600SemiBold", bold: "InstrumentSans_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "instrument-serif": async () => {
    const module = await import("@expo-google-fonts/instrument-serif")
    const sources = { regular: module.InstrumentSerif_400Regular, medium: module.InstrumentSerif_400Regular, semibold: module.InstrumentSerif_400Regular, bold: module.InstrumentSerif_400Regular }
    const aliases = { regular: "InstrumentSerif_400Regular", medium: "InstrumentSerif_400Regular", semibold: "InstrumentSerif_400Regular", bold: "InstrumentSerif_400Regular" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  },
  "geist": async () => {
    const module = await import("@expo-google-fonts/geist")
    const sources = { regular: module.Geist_400Regular, medium: module.Geist_500Medium, semibold: module.Geist_600SemiBold, bold: module.Geist_700Bold }
    const aliases = { regular: "Geist_400Regular", medium: "Geist_500Medium", semibold: "Geist_600SemiBold", bold: "Geist_700Bold" } as const
    const unloaded = Object.entries(sources).filter(([weight]) => !Font.isLoaded(aliases[weight as keyof typeof aliases]))
    if (unloaded.length > 0) {
      await Font.loadAsync(Object.fromEntries(unloaded.map(([weight, source]) => [aliases[weight as keyof typeof aliases], source])))
    }
    return aliases
  }
}

const cache = new Map<PresetFont, Promise<LoadedFontFaces>>()

export function loadPreviewFont(font: PresetFont): Promise<LoadedFontFaces> {
  const cached = cache.get(font)
  if (cached) return cached
  const promise = LOADERS[font]().catch((error) => {
    cache.delete(font)
    throw error
  })
  cache.set(font, promise)
  return promise
}
