// Generated by lovdaCN. Re-run `lovda apply` to change the selected font.
import {
  useFonts,
  SpaceGrotesk_400Regular,
  SpaceGrotesk_500Medium,
  SpaceGrotesk_600SemiBold,
  SpaceGrotesk_700Bold,
} from '@expo-google-fonts/space-grotesk';

export const LVCN_FONT_FACES = {
  regular: 'SpaceGrotesk_400Regular',
  medium: 'SpaceGrotesk_500Medium',
  semibold: 'SpaceGrotesk_600SemiBold',
  bold: 'SpaceGrotesk_700Bold',
} as const;

export function getLvcnFontStyle(className = '') {
  const fontFamily = className.includes('font-bold')
    ? LVCN_FONT_FACES.bold
    : className.includes('font-semibold')
      ? LVCN_FONT_FACES.semibold
      : className.includes('font-medium')
        ? LVCN_FONT_FACES.medium
        : LVCN_FONT_FACES.regular;
  return { fontFamily, fontWeight: 'normal' as const };
}

export function useLvcnFonts() {
  const [loaded, error] = useFonts({
    SpaceGrotesk_400Regular,
    SpaceGrotesk_500Medium,
    SpaceGrotesk_600SemiBold,
    SpaceGrotesk_700Bold,
  });
  if (error) throw error;
  return loaded;
}
