import type { PresetConfig } from "./preset.js"

export type NamedPreset = PresetConfig & {
  title: string
  description: string
}

export const DEFAULT_PRESETS: Record<string, NamedPreset> = {
  "new-york": {
    title: "New York",
    description: "Lucide / Inter / Classic",
    style: "new-york",
    baseColor: "zinc",
    theme: "zinc",
    chartColor: "blue",
    font: "inter",
    iconLibrary: "lucide",
    radius: "default",
  },
  default: {
    title: "Default",
    description: "Lucide / Inter / Standard",
    style: "default",
    baseColor: "slate",
    theme: "slate",
    chartColor: "blue",
    font: "inter",
    iconLibrary: "lucide",
    radius: "default",
  },
  luma: {
    title: "Luma",
    description: "Lucide / Inter / Rounded",
    style: "luma",
    baseColor: "neutral",
    theme: "blue",
    chartColor: "sky",
    font: "inter",
    iconLibrary: "lucide",
    radius: "large",
  },
  lyra: {
    title: "Lyra",
    description: "Phosphor / JetBrains Mono / Tight",
    style: "lyra",
    baseColor: "stone",
    theme: "amber",
    chartColor: "orange",
    font: "jetbrains-mono",
    iconLibrary: "phosphor",
    radius: "small",
  },
  maia: {
    title: "Maia",
    description: "Tabler / Figtree / Rounded",
    style: "maia",
    baseColor: "neutral",
    theme: "violet",
    chartColor: "purple",
    font: "figtree",
    iconLibrary: "tabler",
    radius: "large",
  },
  mira: {
    title: "Mira",
    description: "Phosphor / Inter / Full",
    style: "mira",
    baseColor: "zinc",
    theme: "emerald",
    chartColor: "red",
    font: "inter",
    iconLibrary: "phosphor",
    radius: "full",
  },
  nova: {
    title: "Nova",
    description: "Lucide / Inter / Tight",
    style: "nova",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "blue",
    font: "inter",
    iconLibrary: "lucide",
    radius: "small",
  },
  rhea: {
    title: "Rhea",
    description: "Lucide / DM Sans / Full",
    style: "rhea",
    baseColor: "neutral",
    theme: "rose",
    chartColor: "pink",
    font: "dm-sans",
    iconLibrary: "lucide",
    radius: "full",
  },
  sera: {
    title: "Sera",
    description: "Lucide / Playfair Display / None",
    style: "sera",
    baseColor: "taupe",
    theme: "amber",
    chartColor: "amber",
    font: "playfair-display",
    iconLibrary: "lucide",
    radius: "none",
  },
  vega: {
    title: "Vega",
    description: "Lucide / Space Grotesk / Medium",
    style: "vega",
    baseColor: "neutral",
    theme: "cyan",
    chartColor: "teal",
    font: "space-grotesk",
    iconLibrary: "lucide",
    radius: "medium",
  },
}
