// @ts-nocheck
import * as __fd_glob_45 from "../content/docs/components/tooltip.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/toggle.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/toggle-group.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/textarea.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/text.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/tabs.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/switch.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/separator.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/radio-group.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/progress.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/native-only-animated-view.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/menubar.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/label.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/input.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/icon.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/hover-card.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/context-menu.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/collapsible.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/card.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/aspect-ratio.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/alert.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/alert-dialog.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/accordion.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/(root)/typography.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/(root)/theming.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/(root)/manual.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/(root)/lvcn-json.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/(root)/installation.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/(root)/index.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/(root)/expo-router.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/(root)/dark-mode.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/(root)/cli.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/(root)/changelog.mdx?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/(root)/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "components/meta.json": __fd_glob_1, "(root)/meta.json": __fd_glob_2, }, {"(root)/changelog.mdx": __fd_glob_3, "(root)/cli.mdx": __fd_glob_4, "(root)/dark-mode.mdx": __fd_glob_5, "(root)/expo-router.mdx": __fd_glob_6, "(root)/index.mdx": __fd_glob_7, "(root)/installation.mdx": __fd_glob_8, "(root)/lvcn-json.mdx": __fd_glob_9, "(root)/manual.mdx": __fd_glob_10, "(root)/theming.mdx": __fd_glob_11, "(root)/typography.mdx": __fd_glob_12, "components/accordion.mdx": __fd_glob_13, "components/alert-dialog.mdx": __fd_glob_14, "components/alert.mdx": __fd_glob_15, "components/aspect-ratio.mdx": __fd_glob_16, "components/avatar.mdx": __fd_glob_17, "components/badge.mdx": __fd_glob_18, "components/button.mdx": __fd_glob_19, "components/card.mdx": __fd_glob_20, "components/checkbox.mdx": __fd_glob_21, "components/collapsible.mdx": __fd_glob_22, "components/context-menu.mdx": __fd_glob_23, "components/dialog.mdx": __fd_glob_24, "components/dropdown-menu.mdx": __fd_glob_25, "components/hover-card.mdx": __fd_glob_26, "components/icon.mdx": __fd_glob_27, "components/index.mdx": __fd_glob_28, "components/input.mdx": __fd_glob_29, "components/label.mdx": __fd_glob_30, "components/menubar.mdx": __fd_glob_31, "components/native-only-animated-view.mdx": __fd_glob_32, "components/popover.mdx": __fd_glob_33, "components/progress.mdx": __fd_glob_34, "components/radio-group.mdx": __fd_glob_35, "components/select.mdx": __fd_glob_36, "components/separator.mdx": __fd_glob_37, "components/skeleton.mdx": __fd_glob_38, "components/switch.mdx": __fd_glob_39, "components/tabs.mdx": __fd_glob_40, "components/text.mdx": __fd_glob_41, "components/textarea.mdx": __fd_glob_42, "components/toggle-group.mdx": __fd_glob_43, "components/toggle.mdx": __fd_glob_44, "components/tooltip.mdx": __fd_glob_45, });