// @ts-nocheck
import * as __fd_glob_68 from "../content/docs/(root)/typography.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/(root)/theming.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/(root)/skills.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/(root)/manual.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/(root)/lvcn-json.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/(root)/installation.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/(root)/index.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/(root)/expo-router.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/(root)/dark-mode.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/(root)/cli.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/(root)/charts.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/(root)/changelog.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/blocks/stats-01.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/blocks/signup-03.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/blocks/signup-02.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/blocks/signup-01.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/blocks/login-04.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/blocks/login-03.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/blocks/login-02.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/blocks/login-01.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/blocks/index.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/blocks/dashboard-02.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/blocks/dashboard-01.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/tooltip.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/toggle.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/toggle-group.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/textarea.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/text.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/tabs.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/switch.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/spinner.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/sonner.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/skeleton.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/sidebar.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/sheet.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/separator.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/select.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/radio-group.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/progress.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/popover.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/native-only-animated-view.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/menubar.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/label.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/input.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/input-otp.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/index.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/icon.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/hover-card.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/dialog.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/context-menu.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/collapsible.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/checkbox.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/carousel.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/card.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/calendar.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/button.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/breadcrumb.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/bottom-sheet.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/badge.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/components/avatar.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/components/aspect-ratio.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/components/alert.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/components/alert-dialog.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/components/accordion.mdx?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/blocks/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/(root)/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "(root)/meta.json": __fd_glob_1, "blocks/meta.json": __fd_glob_2, "components/meta.json": __fd_glob_3, }, {"components/accordion.mdx": __fd_glob_4, "components/alert-dialog.mdx": __fd_glob_5, "components/alert.mdx": __fd_glob_6, "components/aspect-ratio.mdx": __fd_glob_7, "components/avatar.mdx": __fd_glob_8, "components/badge.mdx": __fd_glob_9, "components/bottom-sheet.mdx": __fd_glob_10, "components/breadcrumb.mdx": __fd_glob_11, "components/button.mdx": __fd_glob_12, "components/calendar.mdx": __fd_glob_13, "components/card.mdx": __fd_glob_14, "components/carousel.mdx": __fd_glob_15, "components/checkbox.mdx": __fd_glob_16, "components/collapsible.mdx": __fd_glob_17, "components/context-menu.mdx": __fd_glob_18, "components/dialog.mdx": __fd_glob_19, "components/dropdown-menu.mdx": __fd_glob_20, "components/hover-card.mdx": __fd_glob_21, "components/icon.mdx": __fd_glob_22, "components/index.mdx": __fd_glob_23, "components/input-otp.mdx": __fd_glob_24, "components/input.mdx": __fd_glob_25, "components/label.mdx": __fd_glob_26, "components/menubar.mdx": __fd_glob_27, "components/native-only-animated-view.mdx": __fd_glob_28, "components/popover.mdx": __fd_glob_29, "components/progress.mdx": __fd_glob_30, "components/radio-group.mdx": __fd_glob_31, "components/select.mdx": __fd_glob_32, "components/separator.mdx": __fd_glob_33, "components/sheet.mdx": __fd_glob_34, "components/sidebar.mdx": __fd_glob_35, "components/skeleton.mdx": __fd_glob_36, "components/sonner.mdx": __fd_glob_37, "components/spinner.mdx": __fd_glob_38, "components/switch.mdx": __fd_glob_39, "components/tabs.mdx": __fd_glob_40, "components/text.mdx": __fd_glob_41, "components/textarea.mdx": __fd_glob_42, "components/toggle-group.mdx": __fd_glob_43, "components/toggle.mdx": __fd_glob_44, "components/tooltip.mdx": __fd_glob_45, "blocks/dashboard-01.mdx": __fd_glob_46, "blocks/dashboard-02.mdx": __fd_glob_47, "blocks/index.mdx": __fd_glob_48, "blocks/login-01.mdx": __fd_glob_49, "blocks/login-02.mdx": __fd_glob_50, "blocks/login-03.mdx": __fd_glob_51, "blocks/login-04.mdx": __fd_glob_52, "blocks/signup-01.mdx": __fd_glob_53, "blocks/signup-02.mdx": __fd_glob_54, "blocks/signup-03.mdx": __fd_glob_55, "blocks/stats-01.mdx": __fd_glob_56, "(root)/changelog.mdx": __fd_glob_57, "(root)/charts.mdx": __fd_glob_58, "(root)/cli.mdx": __fd_glob_59, "(root)/dark-mode.mdx": __fd_glob_60, "(root)/expo-router.mdx": __fd_glob_61, "(root)/index.mdx": __fd_glob_62, "(root)/installation.mdx": __fd_glob_63, "(root)/lvcn-json.mdx": __fd_glob_64, "(root)/manual.mdx": __fd_glob_65, "(root)/skills.mdx": __fd_glob_66, "(root)/theming.mdx": __fd_glob_67, "(root)/typography.mdx": __fd_glob_68, });