// Generated by packages/lovdacn/scripts/generate-design-system.cjs. Do not edit.

import { Feather, Ionicons, MaterialCommunityIcons } from "@expo/vector-icons"
import * as React from 'react'

import type { IconAdapter } from '../semantic-icon-types'

const GLYPHS = {
  "activity": { IconSet: Feather, name: "activity" },
  "apple": { IconSet: Ionicons, name: "logo-apple" },
  "arrow-right": { IconSet: Feather, name: "arrow-right" },
  "bell": { IconSet: Feather, name: "bell" },
  "book-open": { IconSet: Feather, name: "book-open" },
  "bot": { IconSet: MaterialCommunityIcons, name: "robot" },
  "calendar": { IconSet: Feather, name: "calendar" },
  "chart": { IconSet: Feather, name: "trending-up" },
  "check": { IconSet: Feather, name: "check" },
  "chevron-down": { IconSet: Feather, name: "chevron-down" },
  "chevron-down-icon": { IconSet: Feather, name: "chevron-down" },
  "chevron-left": { IconSet: Feather, name: "chevron-left" },
  "chevron-right": { IconSet: Feather, name: "chevron-right" },
  "chevrons-up-down": { IconSet: Feather, name: "chevrons-up-down" },
  "chevron-up": { IconSet: Feather, name: "chevron-up" },
  "chevron-up-icon": { IconSet: Feather, name: "chevron-up" },
  "close": { IconSet: Feather, name: "x" },
  "command": { IconSet: Feather, name: "command" },
  "credit-card": { IconSet: Feather, name: "credit-card" },
  "dollar": { IconSet: Feather, name: "dollar-sign" },
  "error": { IconSet: Feather, name: "x-circle" },
  "frame": { IconSet: Feather, name: "grid" },
  "gallery": { IconSet: MaterialCommunityIcons, name: "view-gallery-outline" },
  "git-fork": { IconSet: Feather, name: "git-pull-request" },
  "home": { IconSet: Feather, name: "home" },
  "info": { IconSet: Feather, name: "info" },
  "layout-dashboard": { IconSet: Feather, name: "layout" },
  "life-buoy": { IconSet: Feather, name: "life-buoy" },
  "loader": { IconSet: Feather, name: "loader" },
  "loader-2": { IconSet: Feather, name: "loader" },
  "panel-left": { IconSet: Feather, name: "sidebar" },
  "success-2": { IconSet: Feather, name: "check-circle" },
  "alert-circle": { IconSet: Feather, name: "alert-circle" },
  "lock": { IconSet: Feather, name: "lock" },
  "mail": { IconSet: Feather, name: "mail" },
  "menu": { IconSet: Feather, name: "menu" },
  "minus": { IconSet: Feather, name: "minus" },
  "more-horizontal": { IconSet: Feather, name: "more-horizontal" },
  "package": { IconSet: Feather, name: "package" },
  "pie-chart": { IconSet: Feather, name: "pie-chart" },
  "plus": { IconSet: Feather, name: "plus" },
  "search": { IconSet: Feather, name: "search" },
  "settings": { IconSet: Feather, name: "settings" },
  "settings-2": { IconSet: Feather, name: "sliders" },
  "shopping-cart": { IconSet: Feather, name: "shopping-cart" },
  "square-terminal": { IconSet: Feather, name: "terminal" },
  "success": { IconSet: Feather, name: "check-circle" },
  "trending-down": { IconSet: Feather, name: "trending-down" },
  "trending-up": { IconSet: Feather, name: "trending-up" },
  "user": { IconSet: Feather, name: "user" },
  "users": { IconSet: Feather, name: "users" },
  "wallet": { IconSet: Ionicons, name: "wallet-outline" },
  "warning": { IconSet: Feather, name: "alert-triangle" },
} as const

export const expoIconAdapter: IconAdapter = ({
  name,
  size,
  color,
  className,
  accessibilityLabel,
  decorative,
}) => {
  const entry = GLYPHS[name]
  if (!entry) return null
  const { IconSet, name: iconName } = entry
  return (
    <IconSet
      name={iconName as any}
      size={size}
      color={color}
      className={className}
      accessibilityLabel={decorative ? undefined : accessibilityLabel}
      aria-hidden={decorative}
      accessibilityElementsHidden={decorative}
      importantForAccessibility={decorative ? 'no-hide-descendants' : 'auto'}
    />
  )
}
