// Generated by packages/lovdacn/scripts/generate-design-system.cjs. Do not edit.

// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconActivity from "@tabler/icons-react-native/IconActivity"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconBrandApple from "@tabler/icons-react-native/IconBrandApple"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconArrowRight from "@tabler/icons-react-native/IconArrowRight"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconBell from "@tabler/icons-react-native/IconBell"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconBook from "@tabler/icons-react-native/IconBook"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconRobot from "@tabler/icons-react-native/IconRobot"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconCalendar from "@tabler/icons-react-native/IconCalendar"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconChartLine from "@tabler/icons-react-native/IconChartLine"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconCheck from "@tabler/icons-react-native/IconCheck"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconChevronDown from "@tabler/icons-react-native/IconChevronDown"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconChevronLeft from "@tabler/icons-react-native/IconChevronLeft"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconChevronRight from "@tabler/icons-react-native/IconChevronRight"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconSelector from "@tabler/icons-react-native/IconSelector"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconChevronUp from "@tabler/icons-react-native/IconChevronUp"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconX from "@tabler/icons-react-native/IconX"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconCommand from "@tabler/icons-react-native/IconCommand"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconCreditCard from "@tabler/icons-react-native/IconCreditCard"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconCurrencyDollar from "@tabler/icons-react-native/IconCurrencyDollar"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconCircleX from "@tabler/icons-react-native/IconCircleX"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconFrame from "@tabler/icons-react-native/IconFrame"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconLayoutRows from "@tabler/icons-react-native/IconLayoutRows"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconGitFork from "@tabler/icons-react-native/IconGitFork"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconHome from "@tabler/icons-react-native/IconHome"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconInfoCircle from "@tabler/icons-react-native/IconInfoCircle"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconLayoutDashboard from "@tabler/icons-react-native/IconLayoutDashboard"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconLifebuoy from "@tabler/icons-react-native/IconLifebuoy"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconLoader2 from "@tabler/icons-react-native/IconLoader2"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconLayoutSidebar from "@tabler/icons-react-native/IconLayoutSidebar"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconCircleCheck from "@tabler/icons-react-native/IconCircleCheck"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconAlertCircle from "@tabler/icons-react-native/IconAlertCircle"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconLock from "@tabler/icons-react-native/IconLock"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconMail from "@tabler/icons-react-native/IconMail"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconMenu2 from "@tabler/icons-react-native/IconMenu2"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconMinus from "@tabler/icons-react-native/IconMinus"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconDots from "@tabler/icons-react-native/IconDots"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconPackage from "@tabler/icons-react-native/IconPackage"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconChartPie from "@tabler/icons-react-native/IconChartPie"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconPlus from "@tabler/icons-react-native/IconPlus"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconSearch from "@tabler/icons-react-native/IconSearch"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconSettings from "@tabler/icons-react-native/IconSettings"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconAdjustmentsHorizontal from "@tabler/icons-react-native/IconAdjustmentsHorizontal"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconShoppingCart from "@tabler/icons-react-native/IconShoppingCart"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconTerminal2 from "@tabler/icons-react-native/IconTerminal2"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconTrendingDown from "@tabler/icons-react-native/IconTrendingDown"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconTrendingUp from "@tabler/icons-react-native/IconTrendingUp"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconUser from "@tabler/icons-react-native/IconUser"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconUsers from "@tabler/icons-react-native/IconUsers"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconWallet from "@tabler/icons-react-native/IconWallet"
// @ts-expect-error @tabler/icons-react-native@3.46.0 publishes deep declarations one directory too low
import GlyphIconAlertTriangle from "@tabler/icons-react-native/IconAlertTriangle"
import * as React from 'react'

import type { IconAdapter } from '../semantic-icon-types'

const GLYPHS = {
  "activity": GlyphIconActivity,
  "apple": GlyphIconBrandApple,
  "arrow-right": GlyphIconArrowRight,
  "bell": GlyphIconBell,
  "book-open": GlyphIconBook,
  "bot": GlyphIconRobot,
  "calendar": GlyphIconCalendar,
  "chart": GlyphIconChartLine,
  "check": GlyphIconCheck,
  "chevron-down": GlyphIconChevronDown,
  "chevron-down-icon": GlyphIconChevronDown,
  "chevron-left": GlyphIconChevronLeft,
  "chevron-right": GlyphIconChevronRight,
  "chevrons-up-down": GlyphIconSelector,
  "chevron-up": GlyphIconChevronUp,
  "chevron-up-icon": GlyphIconChevronUp,
  "close": GlyphIconX,
  "command": GlyphIconCommand,
  "credit-card": GlyphIconCreditCard,
  "dollar": GlyphIconCurrencyDollar,
  "error": GlyphIconCircleX,
  "frame": GlyphIconFrame,
  "gallery": GlyphIconLayoutRows,
  "git-fork": GlyphIconGitFork,
  "home": GlyphIconHome,
  "info": GlyphIconInfoCircle,
  "layout-dashboard": GlyphIconLayoutDashboard,
  "life-buoy": GlyphIconLifebuoy,
  "loader": GlyphIconLoader2,
  "loader-2": GlyphIconLoader2,
  "panel-left": GlyphIconLayoutSidebar,
  "success-2": GlyphIconCircleCheck,
  "alert-circle": GlyphIconAlertCircle,
  "lock": GlyphIconLock,
  "mail": GlyphIconMail,
  "menu": GlyphIconMenu2,
  "minus": GlyphIconMinus,
  "more-horizontal": GlyphIconDots,
  "package": GlyphIconPackage,
  "pie-chart": GlyphIconChartPie,
  "plus": GlyphIconPlus,
  "search": GlyphIconSearch,
  "settings": GlyphIconSettings,
  "settings-2": GlyphIconAdjustmentsHorizontal,
  "shopping-cart": GlyphIconShoppingCart,
  "square-terminal": GlyphIconTerminal2,
  "success": GlyphIconCircleCheck,
  "trending-down": GlyphIconTrendingDown,
  "trending-up": GlyphIconTrendingUp,
  "user": GlyphIconUser,
  "users": GlyphIconUsers,
  "wallet": GlyphIconWallet,
  "warning": GlyphIconAlertTriangle,
} as const

export const tablerIconAdapter: IconAdapter = ({
  name,
  size,
  color,
  className,
  strokeWidth,
  weight,
  accessibilityLabel,
  decorative,
}) => {
  const Glyph: React.ComponentType<any> = GLYPHS[name]
  return (
    <Glyph
      size={size} color={color} strokeWidth={strokeWidth}
      className={className}
      accessibilityLabel={decorative ? undefined : accessibilityLabel}
      aria-hidden={decorative}
      accessibilityElementsHidden={decorative}
      importantForAccessibility={decorative ? 'no-hide-descendants' : 'auto'}
    />
  )
}
