import fs from 'fs-extra'
import path from 'path'

import {
  FONT_MANIFEST,
  type PresetFont,
} from '../preset/index.js'

const FONT_IMPORT_MARKER = "import { useLvcnFonts } from '@/lib/lvcn-fonts'"
const FONT_READY_MARKER = 'const lvcnFontsReady = useLvcnFonts()'

export function packageNameFromSpecifier(specifier: string): string {
  if (!specifier.startsWith('@')) return specifier.split('@')[0]!
  const versionIndex = specifier.lastIndexOf('@')
  return versionIndex > specifier.indexOf('/') ? specifier.slice(0, versionIndex) : specifier
}

export function getExactFontPackage(font: PresetFont): string {
  const metadata = FONT_MANIFEST[font]
  return `${metadata.package}@${metadata.version}`
}

export function writeProjectFontLoader(projectPath: string, font: PresetFont): string {
  const metadata = FONT_MANIFEST[font]
  const hasSrc = fs.existsSync(path.join(projectPath, 'src'))
  const target = path.join(projectPath, hasSrc ? 'src/lib/lvcn-fonts.ts' : 'lib/lvcn-fonts.ts')
  const faces = metadata.faces
  const content = `// Generated by lovdaCN. Re-run \`lovda apply\` to change the selected font.\nimport {\n  useFonts,\n  ${faces.regular},\n  ${faces.medium},\n  ${faces.semibold},\n  ${faces.bold},\n} from '${metadata.package}'\n\nexport const LVCN_FONT_FACES = {\n  regular: '${faces.regular}',\n  medium: '${faces.medium}',\n  semibold: '${faces.semibold}',\n  bold: '${faces.bold}',\n} as const\n\nexport function getLvcnFontStyle(className = '') {\n  const fontFamily = className.includes('font-bold')\n    ? LVCN_FONT_FACES.bold\n    : className.includes('font-semibold')\n      ? LVCN_FONT_FACES.semibold\n      : className.includes('font-medium')\n        ? LVCN_FONT_FACES.medium\n        : LVCN_FONT_FACES.regular\n  return { fontFamily, fontWeight: 'normal' as const }\n}\n\nexport function useLvcnFonts() {\n  const [loaded, error] = useFonts({\n    ${faces.regular},\n    ${faces.medium},\n    ${faces.semibold},\n    ${faces.bold},\n  })\n  if (error) throw error\n  return loaded\n}\n`
  fs.ensureDirSync(path.dirname(target))
  fs.writeFileSync(target, content, 'utf8')
  return target
}

export function findProjectRootLayout(projectPath: string): string | null {
  const candidates = ['src/app/_layout.tsx', 'app/_layout.tsx', 'src/app/_layout.jsx', 'app/_layout.jsx']
  return candidates.map((file) => path.join(projectPath, file)).find((file) => fs.existsSync(file)) ?? null
}

export function wireProjectFontLoader(projectPath: string): string | null {
  const layoutPath = findProjectRootLayout(projectPath)
  if (!layoutPath) return null
  let content = fs.readFileSync(layoutPath, 'utf8')
  if (!content.includes(FONT_IMPORT_MARKER)) {
    content = `${FONT_IMPORT_MARKER};\n${content}`
  }
  if (!content.includes(FONT_READY_MARKER)) {
    const returnPattern = /\n(\s*)(return\b)/
    if (!returnPattern.test(content)) return null
    content = content.replace(
      returnPattern,
      `\n$1${FONT_READY_MARKER};\n$1if (!lvcnFontsReady) return null;\n\n$1$2`
    )
  }
  fs.writeFileSync(layoutPath, content, 'utf8')
  return layoutPath
}

export function configureProjectFont(projectPath: string, font: PresetFont) {
  return {
    loaderPath: writeProjectFontLoader(projectPath, font),
    layoutPath: wireProjectFontLoader(projectPath),
    packageSpecifier: getExactFontPackage(font),
  }
}
