import fs from "fs-extra"
import path from "path"
import { fileURLToPath } from "url"
import { DEFAULT_REGISTRY_URL } from "../config.js"
import { version } from "../../package.json"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

/**
 * Release channel for registry resolution.
 *
 * The channel is derived from THIS package's version, so the CLI always reads from the
 * registry that was generated by the same release:
 *
 *   1.0.0-beta.7  ->  beta    ->  <base>/beta
 *   0.1.4         ->  stable  ->  <base>
 *
 * The build scripts apply the identical rule when deciding where to WRITE
 * (see scripts/lib/registry-channel.cjs), so `lovdacn@beta` and `r/beta` can never drift
 * apart. Stable installs keep reading `r/*` even after a beta registry is published.
 */
export type RegistryChannel = "stable" | "beta"

/** Explicit override set by a command's `--channel` flag. */
let channelOverride: RegistryChannel | undefined

/** True for any `-beta.*` prerelease version. */
export function isBetaVersion(value: string): boolean {
  return value.includes("-beta.")
}

/**
 * Record an explicit `--channel` choice. Commands call this before resolving any registry
 * item; `LOVDA_REGISTRY_URL` still wins over it.
 */
export function setRegistryChannel(channel: RegistryChannel | undefined) {
  channelOverride = channel
}

/** Active channel: explicit flag first, otherwise derived from the package version. */
export function resolveRegistryChannel(): RegistryChannel {
  if (channelOverride) return channelOverride
  return isBetaVersion(version) ? "beta" : "stable"
}

/** Workspace-relative registry roots, most specific first. */
const LOCAL_REGISTRY_RELATIVE = [
  "../../../apps/v2/public/r",
  "../../../../apps/v2/public/r",
  "../../apps/v2/public/r",
  "../../../../../apps/v2/public/r",
  "../../../../../../apps/v2/public/r",
]

/**
 * Resolve the registry base for the active channel.
 *
 * Precedence:
 *   1. `LOVDA_REGISTRY_URL` — absolute control, used by tests and local registries.
 *   2. A locally served registry inside this workspace (monorepo development).
 *   3. The published registry for the active channel.
 */
export function getRegistryUrl(): string {
  if (process.env.LOVDA_REGISTRY_URL) {
    return process.env.LOVDA_REGISTRY_URL
  }

  const channel = resolveRegistryChannel()
  const suffix = channel === "beta" ? "beta" : ""

  for (const relative of LOCAL_REGISTRY_RELATIVE) {
    const stableRoot = path.resolve(__dirname, relative)
    const localPath = suffix ? path.join(stableRoot, suffix) : stableRoot
    if (fs.existsSync(localPath)) {
      return localPath
    }
  }

  return suffix ? `${DEFAULT_REGISTRY_URL}/${suffix}` : DEFAULT_REGISTRY_URL
}
